name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
      
    - name: Build
      run: |
        yarn build --mac
      env:
        ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
        ELECTRON_BUILDER_BINARIES_MIRROR: https://npmmirror.com/mirrors/electron-builder-binaries/
        
    - name: List dist directory
      run: ls -la dist/
        
    - name: Upload DMG
      uses: actions/upload-artifact@v3
      with:
        name: mac-dmg
        path: dist/*.dmg
        if-no-files-found: error

    - name: Upload Blockmap
      uses: actions/upload-artifact@v3
      with:
        name: mac-blockmap
        path: dist/*.blockmap
        if-no-files-found: warn 