name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        yarn install
      
    - name: Build
      run: |
        yarn build --mac
      env:
        ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
        ELECTRON_BUILDER_BINARIES_MIRROR: https://npmmirror.com/mirrors/electron-builder-binaries/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: List dist directory
      run: ls -la dist/
        
    - name: Create artifact directory
      run: |
        mkdir -p artifacts
        cp dist/*.dmg artifacts/ || true
        cp dist/*.zip artifacts/ || true
        cp dist/*.blockmap artifacts/ || true
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mac-build
        path: artifacts/ 